### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by blade10101** [RNDpacman/blockchain_dns_system#2]
Everything seems to work great, but I was having a issue with log files. It is possible to look at the log files from unbound? Without dumping them to a file that gets crazy huge? I've researched this and it seems to be a issue in docker.

**Comment by RNDpacman** [comment]
You could add something like this in unbound.conf.

```
server:
  log-queries: yes
  log-replies: yes
  logfile: /dev/stdout
  verbosity: 3

```
Copy file to container:
```
docker compose cp ./unbound/unbound.conf unbound:/opt/unbound/etc/unbound/unbound.conf
```
Restart:
```
docker compose restart
```

And watch logs with `docker compose logs unbound` command
